server:
  port: 8095
spring:
  application:
    name: star-module-elderly-server
  main:
    # ğŸ‘‡ğŸ‘‡ğŸ‘‡ åŠ ä¸Šè¿™ä¸€è¡Œï¼Œå…è®¸åŒå Bean è¦†ç›– ğŸ‘‡ğŸ‘‡ğŸ‘‡
    allow-bean-definition-overriding: true
  profiles:
    active: dev  # å½“å‰æ¿€æ´»ç¯å¢ƒ
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml  # æœ¬åœ°åˆ†ç¯å¢ƒæ–‡ä»¶
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml  # Nacos åŒå DataId
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/ruoyi-vue-pro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456 # TODO è¯·ä¿®æ”¹ä¸ºçœŸå®å®‰å…¨å¯†ç 
          driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yaml
        refresh-enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    root: INFO
    cn.start.pp.module.elderly: INFO
